import { ExceptionFilter, Catch, ArgumentsHost, HttpException } from '@nestjs/common';
import { Request, Response } from 'express';
import { QueryFailedError } from 'typeorm';

@Catch(QueryFailedError)
export class TypeormExceptionFilter implements ExceptionFilter {
  catch(exception: QueryFailedError, host: ArgumentsHost) {
    const response = host.switchToHttp().getResponse();
    if (exception) {
      response.status(400).json({ message: 'User already exists.' });
    } else {
      console.log(exception);
      response.status(500).json({ message: 'Internal error.' });
    }
  }
}